src/Entity/Document.php
<?php

namespace App\Entity;

use App\Repository\DocumentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DocumentRepository::class)
 */
class Document
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Chemiin;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    /**
     * @ORM\ManyToOne(targetEntity=Genre::class, inversedBy="documents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $typeId;

    /**
     * @ORM\OneToMany(targetEntity=Acces::class, mappedBy="documentId")
     */
    private $acces;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    public function __construct()
    {
        $this->acces = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getChemiin(): ?string
    {
        return $this->Chemiin;
    }

    public function setChemiin(string $Chemiin): self
    {
        $this->Chemiin = $Chemiin;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getTypeId(): ?Genre
    {
        return $this->typeId;
    }

    public function setTypeId(?Genre $typeId): self
    {
        $this->typeId = $typeId;

        return $this;
    }

    /**
     * @return Collection|Acces[]
     */
    public function getAcces(): Collection
    {
        return $this->acces;
    }

    public function addAcce(Acces $acce): self
    {
        if (!$this->acces->contains($acce)) {
            $this->acces[] = $acce;
            $acce->setDocumentId($this);
        }

        return $this;
    }

    public function removeAcce(Acces $acce): self
    {
        if ($this->acces->removeElement($acce)) {
            // set the owning side to null (unless already changed)
            if ($acce->getDocumentId() === $this) {
                $acce->setDocumentId(null);
            }
        }

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }
}

src/Controller/GedController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;

use App\Entity\Document;
use App\Entity\Genre;
use App\Entity\Acces;
use App\Entity\Utilisateur;
use App\Entity\Autorisation;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\Service\FileUploader;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use DateTime;

class GedController extends AbstractController
{
    /**
     * @Route("/uploadGed", name="uploadGed")
     */
    public function uploadGed(Request $request, EntityManagerInterface $manager): Response
	{
		//Requête pour récupérer toute la table genre
		$listeGenre = $manager->getRepository(Genre::class)->findAll();
		return $this->render('ged/uploadGed.html.twig', [
		'controller_name' => "Upload d'un Document",
		'listeGenre' => $listeGenre,
		'listeUsers' => $manager->getRepository(Utilisateur::class)->findAll(),
		'listeAutorisation' => $manager->getRepository(Autorisation::class)->findAll(),
		]);
	}
	/**
     * @Route("/insertGed", name="insertGed")
     */
public function insertGed(Request $request, EntityManagerInterface $manager): Response
{

		$sess = $request->getSession();
		if($sess->get("idUtilisateur")){
			//création d'un nouveau document
			$Document = new Document();
			//Récupération et transfert du fichier
			//dd($request->request->get('choix'));
			$brochureFile = $request->files->get("fichier");
			if ($brochureFile){
				$newFilename = uniqid('', true) . "." . $brochureFile->getClientOriginalExtension();
				$brochureFile->move($this->getParameter('upload'), $newFilename);
				//insertion du document dans la base.
				if($request->request->get('choix') == "on"){
					$actif=1;
				}else{
					$actif=2;
				}
				$Document->setActif($actif);
				$Document->setNom($request->request->get('nom'));
				$Document->setTypeId($manager->getRepository(Genre::class)->findOneById($request->request->get('genre')));
				$Document->setCreatedAt(new \Datetime);	
				$Document->setChemiin($newFilename);	
				
				$manager->persist($Document);
				$manager->flush();
			}
			//Création d'un acces pour la personne avec laquelle on veut partager le document
			if($request->request->get('utilisateur') != -1){
			$user = $manager->getRepository(Utilisateur::class)->findOneById($request->request->get('utilisateur'));
			$autorisation = $manager->getRepository(Autorisation::class)->findOneById($request->request->get('autorisation'));
			$acces = new Acces();
			$acces->setUtilisateurId($user);
			$acces->setAutorisationId($autorisation);
			$acces->setDocumentId($Document);
			$manager->persist($acces);
			$manager->flush();	
		}
		//Création d'un accès pour l'uploadeur (propriétaire)
		$user = $manager->getRepository(Utilisateur::class)->findOneById($sess->get("idUtilisateur"));
			$autorisation = $manager->getRepository(Autorisation::class)->findOneById(1);
			$acces = new Acces();
			$acces->setUtilisateurId($user);
			$acces->setAutorisationId($autorisation);
			$acces->setDocumentId($Document);
			$manager->persist($acces);
			$manager->flush();
			
			
			return $this->redirectToRoute('listeGed');
		}else{
			return $this->redirectToRoute('authentification');
		}
	}
	/**
     * @Route("/partageGed", name="partageGed")
     */
    public function partageGed(Request $request, EntityManagerInterface $manager): Response
	{
		$sess = $request->getSession();
		if($sess->get("idUtilisateur")){
			//Requête le user en focntion du formulaire
			$user = $manager->getRepository(Utilisateur::class)->findOneById($request->request->get('utilisateur'));
			$autorisation = $manager->getRepository(Autorisation::class)->findOneById($request->request->get('autorisation'));
			$document = $manager->getRepository(Document::class)->findOneById($request->request->get('doc'));
			$acces = new Acces();
			$acces->setUtilisateurId($user);
			$acces->setAutorisationId($autorisation);
			$acces->setDocumentId($document);
			$manager->persist($acces);
			$manager->flush();

			return $this->redirectToRoute('listeGed');
		}else{
			return $this->redirectToRoute('authentification');
		}
	}
	/**
     * @Route("/listeGed", name="listeGed")
     */
    public function listeGed(Request $request, EntityManagerInterface $manager): Response
    {
		$sess = $request->getSession();
		if($sess->get("idUtilisateur")){
			//Requête qui récupère la liste des Users
			$listeGed = $manager->getRepository(Acces::class)->findByUtilisateurID($sess->get("idUtilisateur"));
					
			return $this->render('ged/listeGed.html.twig', [
				'controller_name' => "Liste des Documents",
				'listeGed' => $listeGed,
				'listeUsers' => $manager->getRepository(Utilisateur::class)->findAll(),
				'listeAutorisations' => $manager->getRepository(Autorisation::class)->findAll(),
			]);
		}else{
			return $this->redirectToRoute('authentification');
		}
    }
	/**
     * @Route("/deleteGed/{id}", name="deleteGed")
     */
	  public function deleteGed(Request $request, EntityManagerInterface $manager, Document $id): Response
    {
		$sess = $request->getSession();
		if($sess->get("idUtilisateur")){
			//il faut supprimer le liend dans acces
			$recupListeAcces = $manager->getRepository(Acces::class)->findByDocumentId($id);
			foreach($recupListeAcces as $doc){
				$manager->remove($doc);
				$manager->flush();
			}	
			//supprimer le fichier du disque dur
			//suppression physique du document :
			if(unlink("upload/".$id->getChemiin())){
			//suppression du lien dans la base de données
				$manager->remove($id);
				$manager->flush();
			}
			return $this->redirectToRoute('listeGed');
		}else{
			return $this->redirectToRoute('authentification');
		}
    }
}

templates/ged/listeGed.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des documents{% endblock %}

{% block body %}
<h1>{{ controller_name }}</h1>
<table class="table table-hover">
  <thead>
    <tr>
	  <th scope="col">Id</th>
      <th scope="col">Nom</th>
      <th scope="col">Genre</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
	{% for item in listeGed %}    
	<!-- création de chaque modal -->
		<div class="modal" id="exampleModal{{item.documentId.id}}" tabindex="-1" role="dialog" 	aria-labelledby="exampleModal{{item.documentId.id}}" aria-hidden="true">
		  <div class="modal-dialog" role="document">
			<div class="modal-content">
			  <div class="modal-header">
				<h5 class="modal-title">Partage du document {{ item.documentId.nom }}</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				  <span aria-hidden="true">&times;</span>
				</button>
			  </div>
			  <div class="modal-body">
				<p>
				<!-- début du formulaire de la modal -->
					<form action="/partageGed" method="post">
						<fieldset>
							<legend>Formulaire d'upload</legend>
							<div class="form-group row">
								  <label for="staticNom" class="col-sm-4 col-form-label">Information</label>
								<input class="form-group" type="text" placeholder="{{ item.documentId.nom }}" name="doc" value="{{ item.documentId.id }}" readonly>
							</div>
							<div class="form-group row">
								  <label for="staticNom" class="col-sm-4 col-form-label">Utilisateur</label>
								  <div class="col-sm-8">
									<select class="form-group" name="utilisateur">
											<option class="form-group" value="-1"></option>
										{% for item in listeUsers %}
											<option class="form-group" value= {{ item.id }}>
												{{ item.nom }}  {{ item.prenom }}
											</option>
										{% endfor %}
									</select>
								  </div>
							</div>
							<div class="form-group row">
								  <label for="staticNom" class="col-sm-4 col-form-label">Autorisation</label>
								  <div class="col-sm-18">
									<select class="form-group" name="autorisation">
										{% for item in listeAutorisations %}
											<option class="form-group" value= {{ item.id }}>
												{% if item.ecriture == 1 %} 
													Ecriture 
												{% endif %}
												{% if item.lecture == 1 %} 
													Lecture 
												{% else %}
													Fichier protégé
												{% endif %}
											</option>
										{% endfor %}
									</select>
								  </div>
							</div>
						</fieldset>
					
				<!-- fin du formulaire de la modal -->
				</p>
			  </div>
			  <div class="modal-footer">
				<button type="submit" class="btn btn-primary">Upload</button>
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			  </div>
			  </form>
			</div>
		  </div>
		</div>
	<!-- fin de chaque modal -->
    <tr class="table">
      <th scope="row">{{ item.documentId.id }}</th>
      <td>{{ item.documentId.nom }}</td>
      <td>{{ item.documentId.typeId.type }}</td>
      <td>
		<a href="/deleteGed/{{ item.documentId.id }}"><i class="bi bi-trash"></i></a>
		<a href="/upload/{{ item.documentId.chemiin }}"><i class="bi bi-cloud-download-fill"></i></a>
		{% if item.autorisationId.id == 1 %}
			<a href="#exampleModal{{ item.documentId.id }}" data-toggle="modal" data-target="#exampleModal{{ item.documentId.id }}"><i class="bi bi-share-fill"></i></a>
		{% endif %}
	  </td>
    </tr>
	{% endfor %}
  </tbody>
</table>

{% endblock %}

templates/ged/uploadGed.html.twig
{% extends 'base.html.twig' %}

{% block title %}Upload Ged{% endblock %}

{% block body %}
<div class="example-wrapper">
	<h4> {{ controller_name }} </h4>
</div>
<form action="/insertGed" method="post" enctype="multipart/form-data">
  <fieldset>
    <legend>Formulaire d'upload</legend>
    <div class="form-group row">
      <label for="staticNom" class="col-sm-2 col-form-label">Genre</label>
      <div class="col-sm-10">
        <select class="form-group" name="genre">
			{% for item in listeGenre %}
				<option class="form-group" value= {{ item.id }}>{{ item.type }}</option>
			{% endfor %}
		</select>
      </div>
    </div>
	<div class="form-group row">
      <label for="staticPrenom" class="col-sm-2 col-form-label">Nom</label>
      <div class="col-sm-10">
        <input type="text" class="form-group" id="nom" required name="nom">
      </div>
    </div>
	<div class="form-group row">
      <label for="staticPrenom" class="col-sm-2 col-form-label">Document</label>
      <div class="col-sm-10">
        <input type="file" class="form-group" id="boutonParcourir" name="fichier">
      </div>
    </div>
	<div class="form-group row">
      <label for="staticPrenom" class="col-sm-2 col-form-label">Visible</label>
      <div class="col-sm-10">
        <div class="custom-control custom-switch">
      <input type="checkbox" class="custom-control-input" id="customSwitch1" checked="" name="choix">
      <label class="custom-control-label" for="customSwitch1">Actif / Inactif</label>
    </div>
      </div>
    </div>
	<div class="form-group row">
      <label for="staticNom" class="col-sm-2 col-form-label">Autorisation</label>
      <div class="col-sm-10">
        <select class="form-group" name="autorisation">
			{% for item in listeAutorisation %}
				<option class="form-group" value= {{ item.id }}>
					{% if item.ecriture == 1 %} 
						Ecriture 
					{% endif %}
					{% if item.lecture == 1 %} 
						Lecture 
					{% else %}
						Fichier protégé
					{% endif %}
				</option>
			{% endfor %}
		</select>
      </div>
    </div>
	<div class="form-group row">
      <label for="staticNom" class="col-sm-2 col-form-label">Utilisateur</label>
      <div class="col-sm-10">
        <select class="form-group" name="utilisateur">
				<option class="form-group" value="-1"></option>
			{% for item in listeUsers %}
				<option class="form-group" value= {{ item.id }}>
					{{ item.nom }}  {{ item.prenom }}
				</option>
			{% endfor %}
		</select>
      </div>
    </div>
	</fieldset>
    <button type="submit" class="btn btn-primary">Upload</button>
</form>
{% endblock %}